version: '3.8'

networks:
  client1_network:
    name: client1_network

services:
  mongo_client1:
    image: mongo:6.0
    container_name: mongo_client1
    networks:
      - client1_network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-client1:/data/db

  backend_client1:
    build:
      context: ./Client-1/server
      dockerfile: DockerFile
    container_name: backend_client1
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo_client1:27017/mydb
    depends_on:
      - mongo_client1
    networks:
      - client1_network

  frontend_client1:
    build:
      context: ./Client-1/client
      dockerfile: DockerFile
    container_name: frontend_client1
    ports:
      - "3001:3000"
    depends_on:
      - backend_client1
    networks:
      - client1_network

volumes:
  mongo-data-client1:


