version: '3.8'

networks:
  client2_network:
    name: client2_network

services:
  mongo_client2:
    image: mongo:6.0
    container_name: mongo_client2
    networks:
      - client2_network
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-client2:/data/db

  backend_client2:
    build:
      context: ./Client-2/server
      dockerfile: DockerFile
    container_name: backend_client2
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb://mongo_client2:27017/mydb
    depends_on:
      - mongo_client2
    networks:
      - client2_network

  frontend_client2:
    build:
      context: ./Client-2/client
      dockerfile: DockerFile
    container_name: frontend_client2
    ports:
      - "3002:3000"
    depends_on:
      - backend_client2
    networks:
      - client2_network

volumes:
  mongo-data-client2:
