apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client1-backend
  template:
    metadata:
      labels:
        app: client1-backend
    spec:
      containers:
        - name: client1-backend
          image: kanagaraj1998/test_backend_client1:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
          
