apiVersion: apps/v1
kind: Deployment
metadata:
  name: client1-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client1-frontend
  template:
    metadata:
      labels:
        app: client1-frontend
    spec:
      containers:
        - name: client1-frontend
          image: kanagaraj1998/test_frontend_client2:latest
          ports:
            - containerPort: 3002
