apiVersion: v1
kind: Service
metadata:
  name: client1-backend-service
spec:
  selector:
    app: client1-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP

